package com.novapos.user.domain;

public enum RoleName {
    SUPER_ADMIN,
    SUPPORT_ENGINEER,
    COMPANY_OWNER,
    REGIONAL_MANAGER,
    BRANCH_MANAGER,
    CASHIER,
    SALESPERSON,
    INVENTORY_OFFICER,
    STOREKEEPER,
    WAREHOUSE_MANAGER,
    PURCHASING_OFFICER,
    ACCOUNTANT,
    HR_MANAGER,
    AUDITOR,
    SYSTEM_ADMINISTRATOR,
    CUSTOMER,
    SUPPLIER
}
